#!/bin/bash

# generate configuration file
# 2015-01-11


echo
echo "generate configuration file"
echo 

echo -n "check tmp configuration directory ... "

if [ -d "$TMP_CONF_DIR" ]
then
    echo "exists !"
else
    echo "not exists !"
    echo -n "create temp configuration directory ... "
    if mkdir "$TMP_CONF_DIR" 1>/dev/null 2>/dev/null
    then
        echo "success !"
    else
        echo "fail !"
        exit 1
    fi
fi



echo -n "check configuration file ... "

if [ -f "$TMP_CONF_DIR/$CONF_FILE_NAME" ]
then
    echo "exists , re-generate !"
else
    echo "not exists ,generate !"
fi



echo "generate configuration file ... "

exec 6>&1
exec 1>"$TMP_CONF_DIR/$CONF_FILE_NAME"

echo "#"
echo "# Example Configuration File"
echo "# Date : $(date '+%Y-%m-%d')"
echo "#"
echo

echo "# User Configuration"
echo "user=$ZEUS_USER"
echo 

echo "# Group Configuration"
echo "group=$ZEUS_GROUP"
echo 

echo "# Prefix Directory"
echo "prefix=$ZEUS_PREFIX"
echo 

echo "# Log Directory"
echo "log=$ZEUS_LOG_DIR"
echo

echo "# Pid Directory"
echo "pid=$ZEUS_PID_DIR"
echo

echo "# Port"
echo "port=$ZEUS_PORT"
echo

echo "# Worker Process Number"
echo "worker=$ZEUS_WORKER"
echo

echo "# Timer Resolution"
echo "timer=$ZEUS_RESOLUTION"
echo

echo "# Max Connection"
echo "connection=$ZEUS_MAX_CONNECTION"
echo 

echo "# Manage Password"
echo "manage=$ZEUS_MANAGE_PASSWD"
echo

exec 1>&6
exec 6>&-

echo "configuration file generate successfully !"
