#!/bin/bash


# check headers
# 2015-01-11



BUILD_DIR=build_
BUILD_H=zeus_build.h
SRC_DIR=src
CORE_DIR=core
EVENT_DIR=event
PROTO_DIR=proto
LIB_CHECK_FILE=
ZEUS_SRC_CORE_CHECK_FILE=
ZEUS_SRC_EVENT_CHECK_FILE=
CHECK_FILE_SRC="zeus.$$.check.tmp.c"
CHECK_FILE_OBJ="zeus.$$.check.tmp"



check_file_(){
    
    if [ $# -eq 1 ] || [ $# -eq 2 ]
    then
        :
    else
        echo "check lib headers error"
        exit 1
    fi
    
	if [ $# -eq 1 ]
	then
    	tmp_=$(echo $1 | sed 's/[^\/]*\///g')
	else
		tmp_=$1
	fi

    echo -n "check $tmp_ ... "

    echo "#include \"$1\"" 1>"$BUILD_DIR/$CHECK_FILE_SRC" 2>/dev/null
    echo "int main(void){" 1>>"$BUILD_DIR/$CHECK_FILE_SRC" 2>/dev/null
    echo "return 0;" 1>>"$BUILD_DIR/$CHECK_FILE_SRC" 2>/dev/null
    echo "}" 1>>"$BUILD_DIR/$CHECK_FILE_SRC" 2>/dev/null

    cc "$BUILD_DIR/$CHECK_FILE_SRC" -o "$BUILD_DIR/$CHECK_FILE_OBJ" #1>/dev/null 2>/dev/null

    if [ -f "$BUILD_DIR/$CHECK_FILE_OBJ" ]
    then
        echo "exists !"
    else
        echo "not exists !"
        exit 1
    fi
    
    rm -rf "$BUILD_DIR/$CHECK_FILE_SRC" 1>/dev/null 2>/dev/null
    rm -rf "$BUILD_DIR/$CHECK_FILE_OBJ" 1>/dev/null 2>/dev/null

    return 0

    
}

# create build directory

echo -n "check build directory ... "

if [ -d "$BUILD_DIR" ]
then
    echo "exists !"
else
    echo "not exists !"
    echo -n "create build directory ... "
    if mkdir "$BUILD_DIR" 1>/dev/null 2>/dev/null
    then
        echo "success !"
    else
        echo "fail !"
        exit 1
    fi
fi

# check zeus_build.h

echo -n "check build file ... "

if [ -f "$BUILD_DIR/$BUILD_H" ]
then
	echo "exists , re-generate !"
	if rm -rf "$BUILD_DIR/$BUILD_H"
	then
		:
	else
		echo "re-generate zeus_build.h fail !"
	fi
else
	echo "doesn't exist , generate !"
fi


# create zeus_build.h

echo -n "create build file ... "

if touch "$BUILD_DIR/$BUILD_H" 1>/dev/null 2>/dev/null
then
	echo "success !"
else
	echo "fail !"
	exit 1
fi


# generate the content of zeus_build.h

exec 6>&1
exec 1>"$BUILD_DIR/$BUILD_H"

echo "#ifndef __ZEUS_BUILD_H_H_H__"
echo "#define __ZEUS_BUILD_H_H_H__"

echo 
echo
echo 

echo "#define ZEUS_CONFIGURATION_FILE \"$ZEUS_CONFIG_DIR/$CONF_FILE_NAME\""

echo
echo
echo

echo "#endif"

exec 1>&6
exec 6>&-


# check lib headers

echo 
echo "check lib headers ... "
echo 


LIB_CHECK_FILE="$LIB_CHECK_FILE stdio"
LIB_CHECK_FILE="$LIB_CHECK_FILE stdlib"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/types"
LIB_CHECK_FILE="$LIB_CHECK_FILE unistd"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/time"
LIB_CHECK_FILE="$LIB_CHECK_FILE time"
LIB_CHECK_FILE="$LIB_CHECK_FILE signal"
LIB_CHECK_FILE="$LIB_CHECK_FILE string"
LIB_CHECK_FILE="$LIB_CHECK_FILE fcntl"
LIB_CHECK_FILE="$LIB_CHECK_FILE errno"
LIB_CHECK_FILE="$LIB_CHECK_FILE stdarg"
LIB_CHECK_FILE="$LIB_CHECK_FILE unistd"
LIB_CHECK_FILE="$LIB_CHECK_FILE pwd"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/resource"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/socket"
LIB_CHECK_FILE="$LIB_CHECK_FILE netinet/in"
LIB_CHECK_FILE="$LIB_CHECK_FILE arpa/inet"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/wait"
LIB_CHECK_FILE="$LIB_CHECK_FILE sys/epoll"

for libfile in $LIB_CHECK_FILE
do
    check_file_ "$libfile.h" -1
done



echo
echo "check zeus headers ... "
echo

check_file_ "../$SRC_DIR/$CORE_DIR/zeus_common.h"


ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_alloc"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_buffer"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_config"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_file"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_hash"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_list"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_log"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_process"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_string"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_times"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_connection"
ZEUS_SRC_CORE_CHECK_FILE="$ZEUS_SRC_CORE_CHECK_FILE zeus_signal"

for zeusfile in $ZEUS_SRC_CORE_CHECK_FILE
do
    check_file_ "../$SRC_DIR/$CORE_DIR/$zeusfile.h"
done

check_file_ "../$SRC_DIR/$CORE_DIR/zeus.h"



ZEUS_SRC_EVENT_CHECK_FILE="$ZEUS_SRC_EVENT_CHECK_FILE zeus_event"
ZEUS_SRC_EVENT_CHECK_FILE="$ZEUS_SRC_EVENT_CHECK_FILE zeus_event_io"
ZEUS_SRC_EVENT_CHECK_FILE="$ZEUS_SRC_EVENT_CHECK_FILE zeus_event_timer"
ZEUS_SRC_EVENT_CHECK_FILE="$ZEUS_SRC_EVENT_CHECK_FILE zeus_event_helper"

for zeusfile in $ZEUS_SRC_EVENT_CHECK_FILE
do
	check_file_ "../$SRC_DIR/$EVENT_DIR/$zeusfile.h"
done
