#!/bin/bash

# Install script
# 2015-01-11

exec 6>&1
exec 1>>"Makefile"

echo ".PHONY:install"
echo "install:"

cat<<EOF
	echo -n "check log directory ... "
	(test -d "$ZEUS_LOG_DIR" || mkdir -p "$ZEUS_LOG_DIR") || (echo "create $ZEUS_LOG_DIR fail !" && exit 1)
	echo "success !"
	echo -n "change ownership of log directory ..."
	chown "$ZEUS_USER:$ZEUS_GROUP" $ZEUS_LOG_DIR || (echo "fail !" && exit 1)
	echo "success !"

	echo -n "check pid directory ... "
	test -d "$ZEUS_PID_DIR" || (echo "doesn't exist !" && exit 1)
	echo "success !"

	echo -n "check configuration directory ... "
	test -d "$ZEUS_CONFIG_DIR" || mkdir -p "$ZEUS_CONFIG_DIR" || (echo "create $ZEUS_CONFIG_DIR fail !" && exit 1)
	echo "success !"
	echo -n "change ownership of config directory ..."
	chown "$ZEUS_USER:$ZEUS_GROUP" $ZEUS_CONFIG_DIR || (echo "fail !" && exit 1)
	echo "success !"
	
	echo -n "move configuration file ... "
	cp "$TMP_CONF_DIR/$CONF_FILE_NAME" "$ZEUS_CONFIG_DIR/" || (echo "fail !" && exit 1)
	echo "success !"
EOF

exec 1>&6
exec 6>&-
