#!/bin/bash

# Install script
# 2015-01-11

exec 6>&1
exec 1>>"Makefile"

echo ".PHONY:install"
echo "install:"

cat<<EOF
	(test -d "$ZEUS_LOG_DIR" || mkdir -p "$ZEUS_LOG_DIR") || exit 1
	chown "$ZEUS_USER:$ZEUS_GROUP" $ZEUS_LOG_DIR || exit 1

	(test -d "$ZEUS_PID_DIR" || mkdir -p "$ZEUS_PID_DIR") || exit 1
	chown "$ZEUS_USER:$ZEUS_GROUP" $ZEUS_PID_DIR || exit 1

	test -d "$ZEUS_CONFIG_DIR" || mkdir -p "$ZEUS_CONFIG_DIR" || exit 1
	chown "$ZEUS_USER:$ZEUS_GROUP" $ZEUS_CONFIG_DIR || exit 1
	
	cp "$TMP_CONF_DIR/$CONF_FILE_NAME" "$ZEUS_CONFIG_DIR/" || exit 1
EOF

exec 1>&6
exec 6>&-
